prospector.yml

The current patterns don't ignore all the folder
https://github.com/PyCQA/prospector/blob/master/prospector/profiles/profiles/no_test_warnings.yaml

Ignore rtd_tests folder

---

tasks.py

Automates all the github label pieces so that our labels are the same across
any of our repos. New labels are from
https://github.com/rtfd/readthedocs.org/pull/4180
Also is the foundation for better autochangelog, using pygithub directly

Automate repo label syncing

---

prospector.yml

We don't want to fail the linting when there is no docstring in some places.
Related: https://github.com/rtfd/readthedocs.org/pull/4303#issuecomment-402814388

Ignore missing docstrings in public module/class/method

---

prospector.yml

We do want to support Python 2.x since our Corporate site runs 2.x still.
We skip this check for now and we will re-enable it once all of our code base be under Python 3.x
Related: https://github.com/rtfd/readthedocs.org/pull/4318

Disable useless-object-inheritance since we run linting on Python3

---

isort.cfg
pre-commit-config.yaml
style.yapf

Updated all the plugins and disabled the ones that were failing (`flake8`).
At the moment, we can't get to a status where `pre-commit` works exactly as we want. In other words, the flow we want is:
1. run `pre-commit`
1. some plugins fail but make their changes
1. some other plugins fail and changes are manually done
1. those changes are staged
1. run `pre-commit`
1. all green
Currently, this is not possible for different reasons:
1. we want to sort imports by using `isort` since it's the best one. Although, `yapf` has no option to disable touching the imports. Because of this reason, we need to run first `yapf` (will touch the import and so fail) and _after that_ call `isort` (will touch the imports and fail).
1. for multi lines that do not end on a comma, we want to add the trailing …

Improves for pre-commit configs

---

tasks.py

This was causing this error:
```
File "/Users/eric/projects/readthedocs.org/tasks.py", line 65, in prepare
config.write(configfile)
File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 919, in write
self._sections[section].items(), d)
File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 923, in _write_section
fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```

Fix writing setup.cfg in binary mode.

---

pre-commit-config.yaml

Fixes first part of #30 
I added `--remove` to the plugin and also removed the flake8 check for the encoding.
Besides, as the `--remove` only removes the encoding line, there was an empty line at the beginning of the line. So, to avoid this and get automatically fixed, I'm running first all these small linters (including the one that removes the encoding) and after them the bigger ones `isort`, `yapf`, etc.

Remove encoding

---

isort.cfg

This is not ideal, but solves the issue of a cyclical lint fix when yapf
and isort disagree on the number of lines after imports.

Use default isort lines after import statements

---

tasks.py

It was pointed into `/common` for some reason, requiring the use of
`--path` for prepare. It should be handled automatically.

Fix repo path

---

dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh
dockerfiles/entrypoints/common.sh
dockerfiles/entrypoints/proxito.sh
dockerfiles/entrypoints/web.sh
dockerfiles/requirements.txt
dockerfiles/scripts/create-containers.sh
dockerfiles/scripts/createsuperuser.py
dockerfiles/scripts/wait_for_search.py
dockerfiles/tasks.py
tasks.py

Bring Docker tasks, entrypoints and scripts to common repository so we can use them from .org and .com.
Needed by https://github.com/readthedocs/readthedocs.org/pull/6471 and https://github.com/readthedocs/readthedocs-corporate/pull/767
> Once this PR is merged, we need to upgrade `common` submodule in the other repositories

Bring docker files to share them across repos

---

dockerfiles/docker-compose-search.yml
dockerfiles/docker-compose.yml
dockerfiles/tasks.py

Most of the configs for docker-compose can be shared between community and corporate. This PR bring all the common ones into this repo.

Bring docker-compose common configuration files

---

dockerfiles/tasks.py

This allows us to detach the container using CTRL+p CTRL+q without killing the running process.
See https://docs.docker.com/engine/reference/commandline/attach/

Do not send events to container when attach

---

dockerfiles/docker-compose-search.yml

There is no need to use 512Mb.
Container memory is reduced from ~800 to ~400.

Reduce search container ram to 128Mb

---

dockerfiles/tasks.py

This can be used as `inv docker.compose 'stop nginx'` for example.
It's just a helper to call docker-compose without specifying all the
.yaml files by hand.

`compose` task to pass the command directly to docker-compose

---

dockerfiles/docker-compose-search.yml

This will help with debugging of ES issues,
and let us query it directly instead of having to use a docker shell.

Expose ES to the local machine

---

tasks.py

Normally, each pass, github changelog updates the lock file

Fix issue where npm install of github changelog changes the lock file

---

dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh

Only watch `readthedocs/*.py` and `readthedocsinc/*.py`. This may help
a little with the CPU usage when running with reload enabled.

Reduce number of files watched by watchmedo

---

dockerfiles/docker-compose.yml
dockerfiles/entrypoints/build.sh
dockerfiles/tasks.py

This will give us similar parity with production, where there can't be 2 builds
building in the same server at the same time.
This can be called by,
```
inv docker.up --scale-build 3
```

Use celery concurrency 1 and allow `--scale` containers

---

dockerfiles/docker-compose.yml

If this variable is not defined, Celery fails at startup.
See https://github.com/celery/celery/issues/5761

Define COLUMNS environment variable on celery containers

---

dockerfiles/tasks.py

Required by https://github.com/readthedocs/readthedocs.org/pull/7425 for local development.

Update docker images with new one v8.0

---

dockerfiles/tasks.py

This is required to run `readthedocs-corporate` tests and has no effect in `readthedocs.org`.

Pass `GITHUB_TOKEN` when running tests

---

dockerfiles/docker-compose.yml

I would prefer configurable paths here. If you set environment variables
RTDDEV_PATH_*, this will bubble up to docker compose.
There will be two related PRs that enable theme usage: one for community
and one for corporate.

Add ext-theme and path configuration

---

dockerfiles/docker-compose-webpack.yml
dockerfiles/docker-compose.yml
dockerfiles/entrypoints/webpack.sh
dockerfiles/tasks.py

This enables a few pieces needed for local development of the ext-theme
repository:
* Docker can use ext-theme without webpack, built assets are synced to
storage
* Docker can use ext-theme without webpack, development server starts
and assets are hot reloaded during development
The `docker.up` tasks was reworked to support the additional
configuration in an easier way. Some of the arguments are flipped,
because invoke automatically gives us command arguments like
`--[no-]search` if you specify `search=True`. The `docker.up` help is
currently:
Usage: inv[oke] [--core-opts] docker.up [--options] [other tasks here ...]
Docstring:
Start all the docker containers for a Read the Docs instance
Options:
-e, --ext-theme-enabled   Enable new theme from ext-theme (default: False)
-i, --init …

 Add docker and docker task support for using ext-theme

---

dockerfiles/tasks.py

This allows for running things like `collectstatic` from a running
instance:
inv docker.manage --running collectstatic
Instead of bringing up a new container, an existing container will be
used instead. This allows for the running `web` instance settings to be
reused.

Add `running` flag to `docker.manage` task

---

dockerfiles/tasks.py

Now, when calling `inv docker.shell` (and others) all the commands will be
executed in the container that it's already running (using all the context
already specified, like `--webpack` or `--ext-theme`). For this to work, it's
required to have called `inv docker.up` previously, otherwise the command will
fail saying:
ERROR: No container found for web_1
If you still want to run the command anyways, you can add `--no-running`
argument to the invoke command to spin up a new container just to run that
command.
Closes #76

Make `--running` the default argument on some commands

---

dockerfiles/tasks.py

When calling `inv docker.manage migrate` we can pass `--backupdb` to save an SQL
file with the content of the database before running the migration.
The name of the file uses the current date plus the git commit. This allows us
to go back to the previous state in case it's needed.

Backup PostgreSQL database when running `migrate`

---

dockerfiles/tasks.py

When attaching a container with:
inv docker.attach web
you can now detach it without killing the process with `CTRL-p CTRL-p`. The
default sequence is CTRL-p CTRL-q for containers running with `-i -t` but it
seems that CTRL-q does not get recognized by Invoke for some reason. So, I'm
using CTRL-p CTRL-p for this.
docs.docker.com/engine/reference/commandline/attach

Use `CTRL-p CTRL-p` to detach an attached container

---

dockerfiles/docker-compose.yml

Upgrade postgres database container to match production version, 12.5
To migrate your local data:
```bash
inv docker.up
inv docker.manage --backupdb migrate  # (this should generate a non-empty .sql file)
```
```bash
docker volume rm community_postgres_backups_data community_postgres_data
inv docker.manage 'up database'
docker cp dump.sql community_database_1:/tmp/dump.sql
inv docker.shell --container database
psql -U docs_user docs_db < /tmp/dump.sql
```
Reference: https://github.com/readthedocs/readthedocs.org/issues/7761

Upgrade postgres to v12.5 (production)

---

dockerfiles/docker-compose.yml

We are using 6.0.5 in both, .org and .com now.

Match Redis to production's version

---

dockerfiles/docker-compose.yml

Latest MinIO version requires some changes to use `--console-address`. Also, the
new version of MinIO will require to update the documentation from our
installation guide.
Let's pin it for now to fix the immediate issue and come back with the proper solution.
Solution taken from @astrojuanlu's comment https://github.com/readthedocs/readthedocs.org/issues/8332#issuecomment-878012472

storage: pin minio version

---

dockerfiles/docker-compose.yml

We have better logs in our application with the usage of structlog and these
access logs from NGINX are too noisy. We can always remove these lines locally
if we are doing a in-depth debug for this.

nginx: disable logs by default

---

dockerfiles/docker-compose.yml

Following #89 to upgrade MinIO to its latest version.
Blocked because it requires updating the documentation from https://docs.readthedocs.io/en/latest/development/install.html with the new steps required since the MinIO Console has changed its look&feel.

storage: upgrade MinIO to its latest version

---

dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh

* `--kill-after=5` does not work because there is a bug in watchmedo
* simplify pattern to match all Python files (*.py)
* rely on `--ignore-patterns` to avoid extra files

watchmedo: reload build/celery containers properly

---

dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh

reverts some changes from https://github.com/readthedocs/common/pull/106
Builds are getting stuck because celery is being restarted after the clone step when building a project

Make patterns more specific for watchmedo

---

dockerfiles/entrypoints/build.sh

When a task is revoked, it still needs to be picked up by a worker to "delete it",
in the meantime celery will keep those revoked tasks in memory,
if you restart celery, that list is lost, and the tasks will be executed after a worker picks it up.
Ref https://docs.celeryq.dev/en/stable/userguide/workers.html#persistent-revokes

Celery: keep cancelled builds cancelled

---

dockerfiles/tasks.py

We are now using `ubuntu-20.04` for the clone step. So, that's the required
image now.
Besides, I'm adding `ubuntu-22.04` when all the images are downloaded.

Development: only pull required image

---

dockerfiles/requirements.txt

Without upgrading them, PyYAML fails when compiling it.

Dependencies: upgrade to be compatible with Python 3.10

---

dockerfiles/docker-compose.yml
dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh

Just that. Avoid logging a bunch of unuseful messages and just log INFO ones.
Make usage of an environment variable in case we want to change that from outside.

Development: reduce celery log level from DEBUG to INFO

---

dockerfiles/docker-compose.yml

This was using `latest` on my machine, which was last pulled 2 years ago. Using
an explicit version here for now to avoid this.

Pin Nginx docker image

---

eslintrc

This is so we can use arrow functions, let statements, const, and all other goodies that make JS a little better.

Gulp eslint: allow es6

---

dockerfiles/docker-compose.yml
dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery.sh
dockerfiles/entrypoints/proxito.sh
dockerfiles/entrypoints/web.sh
dockerfiles/nodemon.json

This examples nodemon from the celery entrypoint script to the web and proxito service entrypoint scripts.
The Django runserver --reload option doesn't see to be configurable, and seems to watch a lot of files that are not needed for reloading. I can't tell what exactly is being watched by runserver, but I am getting frequent `too many open files` errors from processes in Docker. Running with --no-reload mostly solves this issue, but requires manually restarting services.
Someone else should spend some time with this, I'm not confident that this will:
1. Fix the issue for others
2. Not cause irreparable damage to your local installation

Use nodemon for reloading on all server processes

---

dockerfiles/docker-compose-webpack.yml
dockerfiles/entrypoints/webpack.sh

This was using a crusty old Node version and was calling `npm install`, so the lock file was being updated and reverted to version 1. This was causing significant spin up time for the docker container.
`npm ci` installs the exact dependencies used in the last build, so we can ensure a CI passing build will match the prod build closely.

Used modern Node for webpack, and us npm ci instead

---

dockerfiles/docker-compose.yml
dockerfiles/tasks.py

It was a little annoying that we had the logging level set to DEBUG since we are flooded wth a lot of messages, even when debugging things.
I set the default logging level to INFO, but added a `log-level=` argument to easily change it in case we want to be more verbose while working locally.

Development: argument to set logging level

---

dockerfiles/entrypoints/proxito.sh
dockerfiles/entrypoints/web.sh

The default is 30 seconds, if you enter in a debugging session, the request will be killed, giving no time to debug.

Remove timeout from web and proxito

---

dockerfiles/nodemon.json

tested and works :+1: 
Updated: When working with changes to `readthedocs.org` that affect readthedocs-corporate, it's nice to have the mounted volume with `readthedocs.org` also cause reloads. Otherwise, it's only changes to the `readthedocs-corporate` repo that causes reloads.

nodemon: monitor readthedocs.org volume

---

dockerfiles/docker-compose.yml
dockerfiles/tasks.py

Trimmed version of https://github.com/readthedocs/common/pull/176

New invoke options: --no-django-debug and --http-proxy (rename)

---

pre-commit-config.yaml

I had to deal with `PYTHONPATH` again and also with `DJANGO_SETTINGS_MODULE` this time. Mainly, I did this work because my PR at https://github.com/readthedocs/readthedocs.org/pull/10355 is failing and it doesn't make sense.
This fixed my issue locally and I hope it fixes the issue on CircleCI as well. Let's see.

pre-commit: update our dependencies

---

prospector.yml

This was super spammy,
and doesn't add any specifi value.

Remove raise-missing-from from pylint warnings

---

dockerfiles/tasks.py

We are not using `latest`, `stable` and `testing` anymore. We are only using Ubuntu images. Download only those 2.

Development: pull down latest Docker images

---

dockerfiles/requirements.txt

Docker Copmose V1 is deprecated and should not be used anymore. The new version, V2, is written in Go and it can't be installed with `pip`.

Development: do not install docker-compose

---

dockerfiles/requirements.txt
dockerfiles/tasks.py

Simplify how we pre-compile `build.tools` on development.

Invoke: `docker.compilebuildtool` command

---

pre-commit-config.yaml

We are using `prospector 1.10` already.

Prospector: remove `PYTHONPATH` hack 

---

pre-commit-config.yaml

It has some extra dependencies that are required to run `prospector`.
Related to https://github.com/readthedocs/readthedocs.org/pull/10240

Install `testing.txt` requirements

---

dockerfiles/docker-compose.yml

This is to avoid stashing/unstashing settings and to push this towards a local `.envrc` file instead, where the secrets can be encrypted. Keeping unencrypted settings in stash history is a pattern to avoid.

Allow passing in Stripe configuration from the host

---

dockerfiles/docker-compose-search.yml

Instead of disabling the whole security package (https://github.com/readthedocs/common/commit/151504fbc8a2b399a6277c92bf549f3168c026b1) we just need to disable HTTPS for Elasticsearch.
I just hit this problem in a fresh environment.

Elasticsearch: disable HTTPS

---

dockerfiles/tasks.py

The old version was removed in https://github.com/readthedocs/common/commit/9932d8a070a387211bf283dd2ff20d2f42af62ed, but we never updated the commands to use the new version.
The docker compose plugin is already included when installing docker from the official site. See https://docs.docker.com/compose/install/. And it's invoked as a subcomand of docker.

Docker: use `docker compose` (v2)

---

isort.cfg
pre-commit-config.yaml

We already ran black on all the codebase, so we should be ready to run black instead of darker.

Lint: we are ready to use Black now

---

dockerfiles/docker-compose.yml

Start a new `wrangler` Docker container for the development worker/server process that executes the JS file.
Related https://github.com/readthedocs/addons/issues/217

Development: use `wrangler` locally (Docker container)

---

dockerfiles/force-readthedocs-addons.js

Remove `/_/static/.../readthedocs-doc-embed.js` that was missing. I think we are using this URL only on development environment.

CF worker: remove `readthedocs-doc-embed.js` proxied

---

dockerfiles/force-readthedocs-addons.js

In https://github.com/readthedocs/readthedocs-ops/pull/1429 we made the selector to remove the "external version warning" a lot more specific.
It fixed the original issue, but it resulted in not matching in other themes. This PR adds extra specific CSS selector for Furo and Book themes.
Closes https://github.com/readthedocs/readthedocs.org/issues/11136

CF worker: remove specific warning admonitions

---

dockerfiles/force-readthedocs-addons.js

We lost this work when moving the `.js` file from the ops repository into community and then again to common.
This is required to be deployed together with addons 0.10.0.
Related:
* https://github.com/readthedocs/readthedocs.org/pull/11126
* https://github.com/readthedocs/addons/issues/211

CF: inject `readthedocs-resolver-filename` HTML meta tag

---

dockerfiles/docker-compose-search.yml
dockerfiles/docker-compose-webpack.yml
dockerfiles/docker-compose.yml

- Version is no longer needed (https://github.com/docker/compose/issues/11628)
- The version of postgres doesn't work with the latest version of docker for some reason, puling that image results in `layers from manifest don't match image configuration`. Also, 12.17 is what we use in production.

Update docker compose files

---

prospector.yml

I'm assuming we shouldn't have checks that conflict with Black,
so removing this.

Remove pydocstyle check that Black doesn't use

---

dockerfiles/docker-compose.yml
dockerfiles/tasks.py

acc68e51 added the ability to customize RTD_PRODUCTION_DOMAIN using the --http-domain argument to docker.up
The Docker Compose settings also allows RTD_PUBLIC_DOMAIN to be configured using an env var but this appears to be unused. Pass http-domain to RTD_PUBLIC_DOMAIN too so that the generated docs can be tested on a custom domain too.
Pass RTD_PUBLIC_DOMAIN to the containers wherever RTD_PRODUCTION_DOMAIN is used.

Dev: Pass http-domain to RTD_PUBLIC_DOMAIN too

---

pre-commit-config.yaml

Those files are copied from other sources or edited by other tools and IMHO not subject for pre-commit handling.
Refs:
- https://github.com/readthedocs/readthedocs.org/issues/11200
- https://github.com/readthedocs/readthedocs.org/pull/11199

Exclude migrations, vendor, .min.js, .svg, and static/*.js from pre-commit

---

dockerfiles/docker-compose.yml
packages/addons-inject/Dockerfile

At some point this pattern got changed and I noticed "invalid arguments" error from Wrangler on starting the container. Swithcing this to entrypoint and only passing in arguments from the docker compose configuration to avoid this all.

Fix wrangler docker again

---

packages/addons-inject/index.js
packages/addons-inject/tests/wrangler.test.js

This header was used for `build.commands` when we were testing addons on those projects that were using our own Sphinx extension to inject the flyout.
That is not required anymore since we have all the projects using the new addons now.
Related https://github.com/readthedocs/readthedocs.org/pull/11653
Closes https://github.com/readthedocs/common/pull/223

CF Worker: remove unused `X-RTD-Hosting-Integrations` HTTP header

---

dockerfiles/Dockerfile.addons
dockerfiles/docker-compose.yml
packages/addons-inject/index.js

With this, running `inv docker.up` will automatically spin up a new container for addons. You can edit the code from your `../addons/` repository and get feedback immediately without reloading.

Spin a Docker container for addons

---

dockerfiles/docker-compose.yml
packages/addons-inject/Dockerfile

I update the wrangler Docker configuration to follow the pattern we already have
for other containers. It mounts only the files that are needed to work and
nothing else.
This is done as an alterntive to #232
that should work for everybody.

Follow current pattern for wrangler container

---

dockerfiles/Dockerfile.addons
dockerfiles/Dockerfile.webpack
dockerfiles/docker-compose-webpack.yml
dockerfiles/docker-compose.yml
dockerfiles/entrypoints/webpack.sh

- Install webpack dependencies inside the Docker image
- Do not call `npm ci` for webpack at startup
- Mount addons volume under `checkouts/` as other containers
- Mount only required directories/files for ext-theme

Docker: standardize Docker compose configuration

---

dockerfiles/docker-compose.yml
dockerfiles/tasks.py

Create a hash of all the dependencies files and use it as a `--build-arg` to invalidate the cache when the hash changes.
Related https://github.com/readthedocs/common/pull/241
Related https://github.com/readthedocs/readthedocs.org/pull/11816

Development: use `--build-arg` to invalidate cache

---

dockerfiles/docker-compose.yml

This is to allow installing dependencies from inside the container and perform the changes in the `package.json` files from the respository itself; so we can push these changes remotely after installing a new dependency.
Covers this use case
https://github.com/readthedocs/common/issues/245#issuecomment-2519778470

Development: mount NPM dependencies files

---

dockerfiles/nodemon.json

I was bitten by this a lot this week. Now, changing code in readthedocs-ext will restart the containers.

Restart Docker containers if readthedocs-ext code changes

---

dockerfiles/docker-compose.yml
dockerfiles/tasks.py

This requires a couple changes:
* Before applying this, you can backup your data with ``inv docker.manage --backupdb shell``. Confirm it worked with `!ls`, which should show a `dump_*.sql` file
* If you keep the same data dir, postgres gets annoyed about the data dir being old, so this swaps a new one.
* After applying, you can run:
```
inv docker.shell --container database --no-running
docker cp dump_*.sql community_database_1:/tmp/dump.sql
createdb -U docs_user docs_db
psql -U docs_user docs_db < dump_*.sql
psql -U docs_user ALTER USER docs_user WITH ENCRYPTED PASSWORD 'docs_pwd';
```

Upgrade Postgres to 16.3 to match prdouction

---

dockerfiles/entrypoints/build.sh
dockerfiles/entrypoints/celery-beat.sh
dockerfiles/entrypoints/celery.sh
dockerfiles/entrypoints/common.sh
dockerfiles/entrypoints/proxito.sh
dockerfiles/entrypoints/web.sh
dockerfiles/tasks.py

When running on Ubuntu 24.04, we cannot use `--system` anymore because pip complains about it. I understand we are forced to create a virtualenv when creating the Docker image.
Due to that, we need to run our application using that virtualenv we created at build time. We use `uv run` for that.
Required by https://github.com/readthedocs/readthedocs.org/pull/12002

Run application from `uv`

---

dockerfiles/docker-compose-search.yml

This breaks ES, as -XX:UseSVE isn't recognized as a valid Java option.
Ref https://github.com/readthedocs/common/pull/270

Restore previous ES option

---

pre-commit-config.yaml

We replaced all of `repos` key with the last update, this removed all other repo configurations.

Fix bad pre-commit config
