- changelog.hbs
Related to https://github.com/rtfd/readthedocs.org/pull/4166
> Use anonymous refs in changelog

- pre-commit-config.yaml
Add minor changes and comment explaining how to run it properly with similar configurations as we have in TravisCI.
> Prospector update config

- isort.cfg
- pre-commit-config.yaml
- prospector.yml
- style.yapf
Many updates to fit our linting preferences.
> Update our linting config

- tasks.py
From https://github.com/rtfd/readthedocs.org/pull/5059#issuecomment-451576094
> Task to upgrade packages

- tasks.py
> Remove `future` dependency as we are in Py3 already

- pre-commit-config.yaml
> Upgrade docformatter 1.1

- pre-commit-config.yaml
- style.yapf
Settings are updated also.
No really important changes, but the new version brings new fixes on their own logic.
> Upgrade yapf to 0.26

- prospector-more.yml
https://github.com/rtfd/readthedocs-corporate/pull/547
> Match api v3

- dockerfiles/docker-compose.yml
> Image of our servers is not shared

- dockerfiles/tasks.py
I found these two operations cumbersome. I don't need all the build
images locally, and in testing changes to build the image, I wanted
caching (I was stuck redownloading dependencies over cafe wifi). Not
caching is sometimes preferable, so we should at least allow the option.
Default is false on both.
I updated the list of images, not sure if it makes sense to also include
the testing image by default though.
> Add more options to docker tasks

- dockerfiles/scripts/create-containers.sh
Required by https://github.com/readthedocs/readthedocs.org/pull/6784
> Azurite CORS headers for containers

- dockerfiles/entrypoints/build.sh
- dockerfiles/entrypoints/celery.sh
- dockerfiles/entrypoints/common.sh
This problem was introduced by myself at https://github.com/readthedocs/common/pull/56
It's not possible to use multiple args for `--patterns` and `--ignore-patterns` :(
> Auto-reload fix

- dockerfiles/entrypoints/build.sh
- dockerfiles/entrypoints/celery.sh
This change is required in Celery 5.x
> Use `celery -A` instead of `celery worker -A`

- prospector.yml
Ref https://github.com/readthedocs/readthedocs.org/pull/8511
> pylint: suppress new rules

- dockerfiles/docker-compose.yml
- dockerfiles/entrypoints/web.sh
- dockerfiles/scripts/createbuckets.sh
Required by https://github.com/readthedocs/readthedocs.org/pull/8853
> MinIO: auto create S3 buckets on `--init`

- dockerfiles/docker-compose.yml
- dockerfiles/entrypoints/postgres.sql
- dockerfiles/entrypoints/web.sh
Ref https://github.com/readthedocs/readthedocs.org/pull/9113
> Docker: use dedicated db for telemetry

- dockerfiles/tasks.py
ref https://github.com/readthedocs/readthedocs.org/pull/9319#discussion_r895914856
> Docker: set project directory explicitily

- dockerfiles/tasks.py
This task will be used to automatically update Django locales from
Transifex (`inv docker.translations --action pull`) and
to push updates from the sources to Transifex as well (`inv docker.translations
--action push`)
Related https://github.com/readthedocs/readthedocs.org/pull/9326
> Translations: define `inv docker.translations` task

- dockerfiles/docker-compose.yml
- dockerfiles/entrypoints/build.sh
- dockerfiles/entrypoints/celery.sh
- dockerfiles/nodemon.json
See https://github.com/readthedocs/readthedocs.org/pull/9338
> Local development: use `nodemon` instead of `watchmedo`

- pre-commit-config.yaml
Closes: https://github.com/readthedocs/readthedocs.org/issues/9502
Related: https://github.com/readthedocs/readthedocs.org/pull/9672
> Add `blacken-docs` in pre-commit hook

- dockerfiles/docker-compose.yml
- dockerfiles/entrypoints/celery-beat.sh
Related https://github.com/readthedocs/readthedocs.org/issues/10003
> Development: spin up a Celery beat container

- pre-commit-config.yaml
Related https://github.com/readthedocs/readthedocs.org/pull/10129
> pre-commit: tweaks after linting our code

- pre-commit-config.yaml
git diffs are funny.. but I moved prospector... not the other two hooks :)
> Run prospector at the end (it's slowest)

- pre-commit-config.yaml
This will allow us to always use newer features intead of old ones.
> Use `django-upgrade` pre-commit hook

- dockerfiles/docker-compose-search.yml
ref https://github.com/readthedocs/readthedocs.org/pull/10771
> Upgrade ES to 8.x

- pre-commit-config.yaml
Ref https://github.com/readthedocs/readthedocs.org/pull/11087
> Add django-safemigrate to pre-commit hooks

- dockerfiles/Dockerfile.wrangler
- dockerfiles/docker-compose.yml
- dockerfiles/force-readthedocs-addons.js
This file was in community before, but it has to be shared with Read the Docs for Business too.
> wrangler: move the Dockerfile to `common/`

- dockerfiles/docker-compose.yml
We need error and auth templates in working in proxito before this can be merged for local development.
- Blocked on https://github.com/readthedocs/ext-theme/issues/304
> Support new dashboard in proxito

- dockerfiles/force-readthedocs-addons.js
We need to know what's the HTTP status for the original request to be able to decide what addons will be enabled. There are some addons we want to disable on 404s for example.
Related: https://github.com/readthedocs/addons/issues/371
> Worker: add HTTP status as meta tag

- packages/addons-inject/tests/wrangler.test.js
Some tests were missing from #228
> CF worker: add missing tests

- dockerfiles/docker-compose.yml
Refs https://github.com/readthedocs/readthedocs.org/pull/11790
> Use RTD_USE_PROMOS

- dockerfiles/docker-compose.yml
Refs https://github.com/readthedocs/readthedocs.org/pull/11873/
> Add FTD env var

- packages/addons-inject/Dockerfile
- packages/addons-inject/package-lock.json
- packages/addons-inject/package.json
I had to update nodejs and wrangler because I was getting an ERROR and wrangler wasn't working anymore.
> Wrangler: update wrangler image

- dockerfiles/Dockerfile.addons
Required by https://github.com/readthedocs/addons/pull/564/
> Update nodejs for addons

- dockerfiles/tasks.py
We are using ext-theme now and these commands are useless now.
Related https://github.com/readthedocs/readthedocs-ops/issues/1600
> Docker: remove assets and translations for legacy dashboard

- dockerfiles/docker-compose.yml
- dockerfiles/tasks.py
Related https://github.com/readthedocs/readthedocs-ops/issues/1600
> New dashboard: remove old legacy dashboard settings
